### ISSUE TITLE
TimeSpeed: change hotkeys to +10 / -10 sec by default with 1 as minimum

### ISSUE THREAD

**Issue by gralewski** [Pathoschild/StardewCommunityMods#3]
First, thank you for great addon.
TS1.0 did however a good job by doubling/halving the time, not changing it by interval.

I have some suggestions.
1. Configurable change:
a) +1 and -1,
b) *2 or /2 (i would prefer this over first one).
2. Add configurable step (interval) to config and change defaults.
The game needs currently left shift being used to adjust the time by more than 1 sec, so both hands on keyboard. I think we change the time speed mostly to quickly fast forward to particular hour or quickly decrease if we need it to nearly stop. I would use +10 / -10 by default, and +1 / -1 by using shift.
3. If decreasing by step, achieve 1 as minimum, not as current multiplier 10 or 100. Currently if i increase by +10 to let's say 20, then i can decrease only to 10. I would like to be able to decrease to 1 always and increase by current step or hotkey, or whatever :)

**Comment by Pathoschild** [comment]
@alexb5dh: you're the main maintainer for TimeSpeed. What do you think of the idea?

**Comment by alexb5dh** [comment]
> Configurable change:
a) +1 and -1,
b) *2 or /2 (i would prefer this over first one).

Option a) is already there and I don't think replacing it with b) now would be a good idea as this will cut tick values that may be used in other scenarios.

> I think we change the time speed mostly to quickly fast forward to particular hour or quickly decrease if we need it to nearly stop. I would use +10 / -10 by default, and +1 / -1 by using shift.

> If decreasing by step, achieve 1 as minimum, not as current multiplier 10 or 100

Agree. Seems like change by 0.1 is redundant, so multiplying all modifiers by 10 and setting lower bound to 1sec for all modifiers would make it simpler.

> so both hands on keyboard

This can be solved by changing increase/decrease hotkeys.

**Comment by gralewski** [comment]
Thank you!
+10 / -10 sec by default with 1 as minimum will be great and sufficient.

**Comment by gralewski** [comment]
Fixed this in my fork.
https://github.com/VerisZG/StardewCommunityMods/blob/develop/TimeSpeed/TimeSpeed.cs
It's my first time contact with VS, C# and GitHub, so if i could done it better, please feel free to tell me.

**Comment by gralewski** [comment]
Oh, this might be of help for you.
https://github.com/VerisZG/StardewCommunityMods/commit/877c5a2a2a8dd80e798505177ca051ec7e9f3e49#diff-aa618d93cf4289ab19f7e4b217a3e33e

**Comment by gralewski** [comment]
So i fixed some things:
1. Changed min value of TickInterval to 0.5 sec.
2. Disabled shift, alt, control modifiers.
3. Set behaviour of changing TickInterval to /2 and *2
4. Changed displaying of time ingame to float from integer.

This is my config now:
{
  "DefaultTickLength": 16.0,
  "TickLengthByLocation": {
    "GreenHouse": 32.0,
    "Cellar": 32.0,
    "UndergroundMine": 128.0
  },
  "EnableOnFestivalDays": true,
  "FreezeTimeAt": null,
  "LocationNotify": true,
  "Keys": {
    "FreezeTime": 78,
    "IncreaseTickInterval": 190,
    "DecreaseTickInterval": 188,
    "ReloadConfig": 66
  }
}

For me personally the addon works better now. Doubling and halving tickinterval scales well and works quickly, there's no need to even use shift etc.
I'm using powers of 2 in config, so numbers are integers with exception of minimum 0.5 sec.

**Comment by alexb5dh** [comment]
@VerisZG, have any suggestions about #5?

**Comment by Pathoschild** [comment]
Closing this since community mods are discontinued.

**Comment by Pathoschild** [comment]
Closing this since community mods are discontinued. All TimeSpeed changes have been merged into [the original repository](https://github.com/cantorsdust/StardewMods).
