### ISSUE TITLE
RecatchLegendaryFish: Support for achievements

### ISSUE THREAD

**Issue by Woden87** [Pathoschild/StardewCommunityMods#6]
If the legendary fish sizes are stored in a temporary dictionary (instead of simply being removed) and re-added to Game1.player.fishCaught during the BeforeSave event, then it *should* allow legendary fish to count towards progress on the fishing achievements if I'm not mistaken.

**Comment by Pathoschild** [comment]
That would help, but fishing achievements are checked when you catch a fish rather than overnight. We'd need one extra step to trigger the achievement check, either in that same event or after catching a fish (e.g. restore the caught legendaries, trigger the achievement checks, then remove them).

**Comment by Pathoschild** [comment]
Done and released in RecatchLegendaryFish 1.4. :)
