### ISSUE TITLE
TractorMod: replace garage sprite

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/StardewCommunityMods#7]
The tractor garage currently looks like this:
> ![](https://cloud.githubusercontent.com/assets/230581/25956829/cab335c0-363a-11e7-8b00-0ff4a20a6dc6.png)

...which is fine, but it doesn't fit in with the game very well. Consider replacing the garage sprite with one that looks like Robin built it, instead of a JojaMart competitor.

**Comment by Acerbicon** [comment]
I wholeheartedly agree to release this under the same MIT license as TractorMod, here ya go!
![tractorhouse](https://cloud.githubusercontent.com/assets/18371051/25956998/4265cdc6-363b-11e7-9b2c-9afcaeba06d5.png)

**Comment by Pathoschild** [comment]
That looks amazing. Here's how it looks in the game:
> ![](https://cloud.githubusercontent.com/assets/230581/25967601/bc2c675c-365c-11e7-9f2f-2ac75ee91f79.png)

Thanks!
