### ISSUE TITLE
TractorMod: replace tractor sprite

### ISSUE THREAD

**Issue by Pathoschild** [Pathoschild/StardewCommunityMods#8]
Here's the current tractor spritesheet:
![tractor](https://cloud.githubusercontent.com/assets/230581/25968593/0c131b1e-3660-11e7-9997-ffdabd5c366a.png)

Unfortunately it was [created by another author](http://community.playstarbound.com/threads/108604/page-2#post-3069968), so it can't be released under the MIT license along with the rest of TractorMod. Replace it with a new sprite that can be open-sourced too.

**Comment by Zero-ui9** [comment]
I've made new textures, and am releasing them under the same MIT license as TractorMod.

![tractor](https://user-images.githubusercontent.com/14851471/28254156-3021e80e-6a78-11e7-8264-e99f98d80b07.png)

https://www.dropbox.com/s/3kduhcm4u5dbgif/tractor.xnb?dl=0

**Comment by Pathoschild** [comment]
Thanks a lot! It looks great in-game:
> ![tractor garage](https://user-images.githubusercontent.com/230581/28256077-ba35cd80-6a8c-11e7-983e-f4ffd4d17d21.png)
> ![tractor](https://user-images.githubusercontent.com/230581/28256254-772598e8-6a8e-11e7-8a70-353ca74cbd36.gif)

There's a few more changes I want to make, and then TractorMod 4.0 will be ready for release. :)

**Comment by Zero-ui9** [comment]
In your gif, when you're moving downwards there's this small, dark grey line that appears on the front of the tractor, and it bobs with the player. Whats that from? I certainly don't see it in my own game(from replacing the horse texture). Also, I'm glad you like you like it! I figured the dull green/grey would fit well with the garage (:

**Comment by Pathoschild** [comment]
That seems to be a bug with the Get Dressed mod; nothing wrong with the tractor itself. :)

**Comment by skippersmith** [comment]
When I download the mod Tractor, I can not find the dll, when I run the error saying that the dll does not exist
![erro trator](https://user-images.githubusercontent.com/30448273/29040694-5e7f3228-7b86-11e7-8144-79576d569f74.jpg)
