### ISSUE TITLE
TractorMod: Cannot Find its XNBs With Latest SDVMM

### ISSUE THREAD

**Issue by Exaxxion** [Pathoschild/StardewCommunityMods#9]
Versions:
- Stardew: 1.2.31
- SDVMM: 3.1g
- SMAPI: 1.15.1
- TractorMod: 3.2.1

When I install this mod and press 'N' to call PhthaloBlue I get stuck in a menu loop that throws the following error when I click either option, requiring the game to be force-closed:

>[14:51:14 ERROR SMAPI] An error occured in the base update loop: Microsoft.Xna.Framework.Content.ContentLoadException: Error loading "..\Mods\TractorMod\assets\TractorHouse". File not found. ---> System.IO.FileNotFoundException: Error loading "Mods\TractorMod\assets\TractorHouse.xnb". File not found.
>   at Microsoft.Xna.Framework.TitleContainer.OpenStream(String name)
>   at Microsoft.Xna.Framework.Content.ContentManager.OpenStream(String assetName)
>   --- End of inner exception stack trace ---
>   at Microsoft.Xna.Framework.Content.ContentManager.OpenStream(String assetName)
>   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
>   at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName)
>   at StardewValley.LocalizedContentManager.Load[T](String assetName)
>   at StardewModdingAPI.Framework.SContentManager.Load[T](String assetName) in D:\source\_Stardew\SMAPI\src\StardewModdingAPI\Framework\SContentManager.cs:line 135
>   at TractorMod.TractorMod.OpenPhthaloBlueCarpenterMenu(Farmer who, String whichAnswer) in D:\source\_Stardew\TractorMod\TractorMod\TractorMod.cs:line 914
>   at StardewValley.GameLocation.answerDialogue(Response answer)
>   at StardewValley.Menus.DialogueBox.receiveLeftClick(Int32 x, Int32 y, Boolean playSound)
>   at StardewValley.Game1.updateActiveMenu(GameTime gameTime)
>   at StardewValley.Game1.Update(GameTime gameTime)
>   at StardewModdingAPI.Framework.SGame.Update(GameTime gameTime) in D:\source\_Stardew\SMAPI\src\StardewModdingAPI\Framework\SGame.cs:line 593

The file `TractorHouse.xnb` mentioned in the error is in `<installDir>\Mods\9-TractorMod\assets\` which is the likely cause of this error. It seems that SDVMM at some point started doing some kind of weird numbering thing which breaks the mod's expected asset path. Not sure if this is something you can fix or if it's an issue to report to SDVMM.

**Comment by Exaxxion** [comment]
As a workaround I manually removed the numbering prefixes from the mod folders. I believe the numbering is related to SDVMM's load order feature.

**Comment by Pathoschild** [comment]
That's already fixed in the upcoming TractorMod release, since it uses SMAPI's new content API instead. :)
